### ISSUE TITLE
Feature Center Center

### ISSUE THREAD

**Issue by IRediTOTO** [bostrom/text-to-image#69]
Hi, can you please add one more feature vertical cecnter? 
I want text Will center of box.

**Comment by bostrom** [comment]
@IRediTOTO Thanks for your request. Do you mean vertical center when using customHeight? Can you give a code example of an image you generate where you'd like the text to be vertically centered?

**Comment by OsirisFrik** [comment]
Hi, im to want this feature please, this is mi example options to generate image:
```
{
    bgColor: randomcolor(),
    textAlign: 'center',
    maxWidth: 100,
    customHeight: 80,
    textColor: '#FFF',
    fontSize: 30
}
```

I gonna try to implement the feature, and send the PR

**Comment by bostrom** [comment]
Thanks @OsirisFrik, try to get it started and I can help out once you have your PR open.

**Comment by OsirisFrik** [comment]
@bostrom i have a little problem with eslint

<img width="485" alt="Screen Shot 2021-04-05 at 3 06 51 PM" src="https://user-images.githubusercontent.com/9331532/113632742-9520b280-9620-11eb-94b3-e0142a714b11.png">

look my `index.d.ts` because I don't find the error 
<img width="569" alt="Screen Shot 2021-04-05 at 3 07 20 PM" src="https://user-images.githubusercontent.com/9331532/113632778-a2d63800-9620-11eb-8b5e-2bf7e4a44fff.png">
